# Generated by Django 2.0 on 2018-01-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0002_auto_20180121_1744'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('perms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Perm',
        ),
    ]
