# Generated by Django 2.0 on 2018-03-15 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saltgroup',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 15, 7, 28, 57, 26823, tzinfo=utc), verbose_name='Create at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saltgroup',
            name='create_by',
            field=models.CharField(default=1, max_length=50, verbose_name='Create by'),
            preserve_default=False,
        ),
    ]
