# Generated by Django 2.0 on 2018-03-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.CharField(max_length=15, verbose_name='City'),
        ),
    ]
