# Generated by Django 2.0 on 2018-03-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180308_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='kernel',
            new_name='kernelrelease',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='cpu_nums',
            new_name='num_cpus',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='os',
            new_name='osrelease',
        ),
        migrations.RemoveField(
            model_name='server',
            name='minion',
        ),
        migrations.AddField(
            model_name='server',
            name='num_gpus',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='gpu_nums'),
        ),
    ]
