# Generated by Django 2.0 on 2018-03-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180326_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='esc',
        ),
        migrations.RemoveField(
            model_name='server',
            name='maintain',
        ),
        migrations.RemoveField(
            model_name='server',
            name='purchase_date',
        ),
    ]
