# Generated by Django 2.0 on 2018-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180326_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='HostName'),
        ),
    ]
