# Generated by Django 2.0 on 2018-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180411_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='HostName'),
        ),
    ]
