# Generated by Django 2.0 on 2018-04-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20180413_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='container id')),
                ('nodeId', models.IntegerField(verbose_name='node id')),
                ('status', models.CharField(max_length=30, verbose_name='container status')),
                ('createTime', models.CharField(max_length=50, verbose_name='createTime')),
                ('startTime', models.CharField(max_length=50, verbose_name='startTime')),
                ('stopTime', models.CharField(max_length=50, verbose_name='stopTime')),
                ('hostId', models.IntegerField(verbose_name='hostId')),
                ('cpu', models.CharField(max_length=5, verbose_name='cpu')),
                ('mem', models.CharField(max_length=8, verbose_name='mem')),
                ('disk', models.CharField(max_length=8, verbose_name='disk')),
                ('health', models.CharField(max_length=10, verbose_name='health')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='image id')),
                ('imageName', models.CharField(max_length=150, verbose_name='imageName')),
                ('imageTag', models.CharField(max_length=50, verbose_name='imageTag')),
                ('imageAlias', models.CharField(max_length=100, verbose_name='imageAlias')),
                ('ImageModifyTime', models.CharField(max_length=100, verbose_name='ImageModifyTime')),
            ],
            options={
                'ordering': ['imageName'],
                'permissions': (('view_image', 'view image'), ('chanage_image', 'chanage image')),
            },
        ),
    ]
