# Generated by Django 2.0 on 2018-04-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_container_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='host id')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='host name')),
                ('instanceName', models.CharField(max_length=70, verbose_name='instanceName')),
                ('instanceId', models.CharField(max_length=120, unique=True, verbose_name='instanceId')),
                ('internetIp', models.CharField(max_length=15, verbose_name='internetIp')),
                ('intranetIp', models.CharField(max_length=15, verbose_name='intranetIp')),
                ('status', models.CharField(max_length=10, verbose_name='status')),
                ('connectivity', models.BooleanField(verbose_name='connectivity')),
                ('regionId', models.IntegerField(verbose_name='regionId')),
                ('regionDisplay', models.CharField(max_length=30, verbose_name='regionDisplay')),
                ('cpu', models.CharField(max_length=11, verbose_name='cpu')),
                ('cpuUsed', models.CharField(max_length=10, verbose_name='cpuUsed')),
                ('memory', models.CharField(max_length=11, verbose_name='memory')),
                ('memUsed', models.CharField(max_length=11, verbose_name='memUsed')),
                ('diskSize', models.CharField(max_length=11, verbose_name='diskSize')),
                ('diskUsed', models.CharField(max_length=11, verbose_name='diskUsed')),
                ('containerCount', models.IntegerField(verbose_name='containerCount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
