# Generated by Django 2.0 on 2018-04-15 05:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='nodeId')),
                ('name', models.CharField(max_length=30, verbose_name='nodeName')),
                ('imageName', models.CharField(max_length=50, verbose_name='imageName')),
                ('status', models.CharField(max_length=15, verbose_name='status')),
                ('serviceId', models.IntegerField(verbose_name='serviceId')),
                ('createTime', models.CharField(max_length=70, verbose_name='createTime')),
                ('containers', jsonfield.fields.JSONField(verbose_name='containers')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
