# Generated by Django 2.0 on 2018-04-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_node'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id'], 'permissions': (('view_image', 'view image'), ('chanage_image', 'chanage image'))},
        ),
    ]
