# Generated by Django 2.0 on 2018-04-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20180415_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id']},
        ),
    ]
