# Generated by Django 2.0 on 2018-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20180415_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='health',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='health'),
        ),
    ]
