# Generated by Django 2.0 on 2018-04-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_auto_20180415_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='stopTime',
            field=models.CharField(max_length=50, null=True, verbose_name='stopTime'),
        ),
    ]
