# Generated by Django 2.0 on 2018-04-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_auto_20180415_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='startTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='startTime'),
        ),
        migrations.AlterField(
            model_name='container',
            name='stopTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='stopTime'),
        ),
    ]
