# Generated by Django 2.0 on 2018-04-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpAlarmPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='alarm policy')),
                ('code', models.CharField(max_length=5, verbose_name='status code')),
                ('timeout', models.CharField(max_length=10, verbose_name='timeout')),
                ('step', models.CharField(max_length=5, verbose_name='max_step')),
                ('times', models.CharField(blank=True, max_length=5, null=True, verbose_name='times')),
                ('keywords', models.CharField(blank=True, max_length=50, null=True, verbose_name='keywords')),
                ('create_by', models.CharField(max_length=50, verbose_name='Create by')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='HttpEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='env url')),
                ('status', models.CharField(max_length=5, verbose_name='status')),
                ('ipaddress', models.CharField(max_length=20, verbose_name='IPAddress')),
                ('event_time', models.IntegerField(verbose_name='event time')),
                ('resp_time', models.IntegerField(verbose_name='response time')),
                ('resp_code', models.IntegerField(verbose_name='code')),
                ('result', models.IntegerField(verbose_name='result')),
                ('currentstep', models.IntegerField(verbose_name='current step')),
                ('maxstep', models.IntegerField(verbose_name='max step')),
            ],
            options={
                'ordering': ['event_time'],
            },
        ),
        migrations.CreateModel(
            name='HttpMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(db_index=True, verbose_name='http url')),
                ('service', models.CharField(max_length=50, verbose_name='desc')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('create_by', models.CharField(max_length=50, verbose_name='Create by')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('alarmploicy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.HttpAlarmPolicy', verbose_name='http alarm policy')),
            ],
            options={
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='HttpMonitorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='http group')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('create_by', models.CharField(max_length=50, verbose_name='Create by')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='httpmonitor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.HttpMonitorGroup', verbose_name='http group'),
        ),
    ]
