# Generated by Django 2.0 on 2018-04-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Http',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='http name')),
                ('url', models.URLField(verbose_name='http url')),
            ],
        ),
        migrations.AlterField(
            model_name='httpalarmpolicy',
            name='create_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Create by'),
        ),
    ]
