# Generated by Django 2.0 on 2018-04-10 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='project name')),
                ('abbr_name', models.SlugField(unique=True, verbose_name='project abbr name')),
                ('code_address', models.URLField(verbose_name='gitlab url')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='project owner')),
            ],
        ),
    ]
