# Generated by Django 2.0 on 2018-04-10 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='create_by',
            field=models.CharField(default=1, max_length=50, verbose_name='Create by'),
            preserve_default=False,
        ),
    ]
