# Generated by Django 2.0 on 2018-04-13 06:40

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_projectenv'),
    ]

    operations = [
        migrations.CreateModel(
            name='EwsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Service Name')),
                ('imageName', models.CharField(max_length=100, verbose_name='Image Name')),
                ('createtime', models.DateTimeField(verbose_name='Create at')),
                ('regionDisplay', models.CharField(max_length=50, verbose_name='Region')),
                ('nodes', jsonfield.fields.JSONField(verbose_name='Node List')),
            ],
            options={
                'permissions': (('view_service', 'view service'), ('refresh_service', 'refresh serice')),
            },
        ),
    ]
