# Generated by Django 2.0 on 2018-04-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_ewsservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EwsService',
            new_name='Service',
        ),
    ]
