# Generated by Django 2.0 on 2018-04-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20180413_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='createtime',
            new_name='createTime',
        ),
    ]
