# Generated by Django 2.0 on 2018-04-14 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20180413_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectenv',
            name='name',
        ),
        migrations.AddField(
            model_name='projectenv',
            name='service',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.Service', verbose_name='service'),
            preserve_default=False,
        ),
    ]
