# Generated by Django 2.0 on 2018-04-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20180414_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenv',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.Project', verbose_name='Project'),
            preserve_default=False,
        ),
    ]
