# Generated by Django 2.0 on 2018-04-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_projectenv_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectenv',
            options={'ordering': ['project']},
        ),
    ]
