# Generated by Django 2.0 on 2018-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20180414_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenv',
            name='name',
            field=models.CharField(choices=[('prod', '生产环境'), ('pre', '预发环境')], default=1, max_length=5, verbose_name='env'),
            preserve_default=False,
        ),
    ]
