# Generated by Django 2.0 on 2018-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_projectenv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenv',
            name='name',
            field=models.CharField(choices=[('prod', '生产环境'), ('pre', '预发环境')], max_length=5, unique=True, verbose_name='env'),
        ),
    ]
