# Generated by Django 2.0 on 2018-04-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20180414_2340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectenv',
            unique_together={('name', 'project')},
        ),
    ]
