# Generated by Django 2.0 on 2018-04-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20180415_0007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectenv',
            unique_together={('name', 'project', 'service')},
        ),
    ]
