# Generated by Django 2.0 on 2018-04-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20180415_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenv',
            name='name',
            field=models.CharField(choices=[('prod', '生产环境'), ('pre', '预发环境')], max_length=5, verbose_name='env'),
        ),
    ]
